name: Zensical Documentation

on:
  push:
    branches:
      - '**'

jobs:
  build_and_validate:
    name: Build & Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install zensical

      - name: Build Zensical
        run: zensical build --clean

  rtd:
    if: github.ref == 'refs/heads/main' && success()
    name: Trigger Read the Docs
    runs-on: ubuntu-latest
    needs: build_and_validate
    
    steps:
      - name: API Build Trigger
        run: |
          curl -X POST \
            -H "Authorization: Token ${{ secrets.RTD_TOKEN }}" \
            "https://app.readthedocs.org/api/v3/projects/wirewolves-documentation/versions/latest/builds/"